#!/bin/bash
python opt.py --matrix_data "./diff_prop_sim_smallnoise/avg_prop_1/sim_matrix_data.csv" --study_names "./diff_prop_sim_smallnoise/avg_prop_1/sim_study_name.csv" --output_path "./diff_prop_sim_smallnoise/avg_prop_1/output" --rank 20
python opt.py --matrix_data "./diff_prop_sim_smallnoise/avg_prop_2/sim_matrix_data.csv" --study_names "./diff_prop_sim_smallnoise/avg_prop_2/sim_study_name.csv" --output_path "./diff_prop_sim_smallnoise/avg_prop_2/output" --rank 20
python opt.py --matrix_data "./diff_prop_sim_smallnoise/avg_prop_3/sim_matrix_data.csv" --study_names "./diff_prop_sim_smallnoise/avg_prop_3/sim_study_name.csv" --output_path "./diff_prop_sim_smallnoise/avg_prop_3/output" --rank 20
python opt.py --matrix_data "./diff_prop_sim_smallnoise/avg_prop_4/sim_matrix_data.csv" --study_names "./diff_prop_sim_smallnoise/avg_prop_4/sim_study_name.csv" --output_path "./diff_prop_sim_smallnoise/avg_prop_4/output" --rank 20
python opt.py --matrix_data "./diff_prop_sim_smallnoise/avg_prop_5/sim_matrix_data.csv" --study_names "./diff_prop_sim_smallnoise/avg_prop_5/sim_study_name.csv" --output_path "./diff_prop_sim_smallnoise/avg_prop_5/output" --rank 20
python opt.py --matrix_data "./diff_prop_sim_smallnoise/avg_prop_6/sim_matrix_data.csv" --study_names "./diff_prop_sim_smallnoise/avg_prop_6/sim_study_name.csv" --output_path "./diff_prop_sim_smallnoise/avg_prop_6/output" --rank 20
python opt.py --matrix_data "./diff_prop_sim_smallnoise/avg_prop_7/sim_matrix_data.csv" --study_names "./diff_prop_sim_smallnoise/avg_prop_7/sim_study_name.csv" --output_path "./diff_prop_sim_smallnoise/avg_prop_7/output" --rank 20
python opt.py --matrix_data "./diff_prop_sim_smallnoise/avg_prop_8/sim_matrix_data.csv" --study_names "./diff_prop_sim_smallnoise/avg_prop_8/sim_study_name.csv" --output_path "./diff_prop_sim_smallnoise/avg_prop_8/output" --rank 20
python opt.py --matrix_data "./diff_prop_sim_smallnoise/avg_prop_9/sim_matrix_data.csv" --study_names "./diff_prop_sim_smallnoise/avg_prop_9/sim_study_name.csv" --output_path "./diff_prop_sim_smallnoise/avg_prop_9/output" --rank 20